language: node_js
node_js: 0.11
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/report-lcov/lcov.info
services: mongodb
addons:
  code_climate:
    repo_token: e4ac77f28625f3e0edb1f44aae17436f2a33c2834ae270b56c103f1183c63642
